const AfricanCountryList = [
  { GeoLocation: 'String' },
  { CountryAbbrv: 'String' },
  { CountryName: 'string' },
  { AreaCode: Number },
  { officialLanguage: 'string' },
  { Capital: 'string' },
  { Currency: 'string' },
  { Flag: 'string' },
  { Capital: 'string' },
  { Currency: 'string' },
  //  futureConnections  =  "Internet users"
  { futureConnections: Number },
  { Population: Number },
];

//North Africa_(1-8)
//East Africa_(9-28)
//South Africa_(29-33)
//West Africa_(34-50)
//Central Africa_(51-59)

AfricanCountryList = {
  //North Africa__(1-8)_________________________________________________________________________________________________________________________
  1: {
    GeoLocation: 'North',
    CountryAbbrv: 'DZ',
    CountryName: 'Algeria',
    AreaCode: 213,
    officialLanguage: 'Arabic',
    Capital: 'Algiers',
    Currency: 'Algerian dinar',
    Flag: '🇩🇿',
    futureConnections: 4700000,
    Population: 38813722,
  },

  2: {
    GeoLocation: 'North',
    CountryAbbrv: 'EG',
    CountryName: 'Egypt',
    AreaCode: 20,
    officialLanguage: 'Arabic',
    Capital: 'Cairo',
    Currency: 'Egyptian Pound',
    'Country Flag': '🇪🇬',
    futureConnections: 20136000,
    Population: 86895099,
  },

  3: {
    GeoLocation: 'North',
    CountryAbbrv: 'LY',
    CountryName: 'Libya',
    AreaCode: 218,
    officialLanguage: 'Arabic',
    Capital: 'Tripoli',
    Currency: 'Libyan dinar',
    'Country Flag': '🇱🇾',
    futureConnections: 353900,
    Population: 6244174,
  },

  4: {
    GeoLocation: 'North',
    CountryAbbrv: 'MA',
    CountryName: 'Morocco',
    AreaCode: 212,
    officialLanguage: 'Arabic',
    Capital: 'Rabat',
    Currency: 'Moroccan dirham',
    'Country Flag': '🇲🇦',
    futureConnections: 13213000,
    Population: 32987206,
  },

  5: {
    GeoLocation: 'North',
    CountryAbbrv: 'TN',
    CountryName: 'Tunisia',
    AreaCode: 216,
    officialLanguage: 'Arabic',
    Capital: 'Tunis',
    Currency: 'Tunisian dinar',
    'Country Flag': '🇹🇳',
    futureConnections: 3500000,
    Population: 10937521,
  },

  6: {
    GeoLocation: 'North',
    CountryAbbrv: 'SD',
    CountryName: 'Sudan',
    AreaCode: 249,
    officialLanguage: 'Arabic',
    Capital: 'Khartoum',
    Currency: 'Sudanese Pound',
    Flag: '🇸🇩',
    futureConnections: 4200000,
    Population: 35482233,
  },

  7: {
    GeoLocation: 'North',
    CountryAbbrv: 'EH',
    CountryName: 'Western Sahara',
    Capital: 'Laayoune',
    Currency: 'Sahrawi peseta, Moroccan dirham',
    'Country Flag': '🇲🇦/🇪🇭',
  },

  8: {
    GeoLocation: 'North',
    CountryAbbrv: 'ES-CN',
    CountryName: 'Canary Islands',
    Capital: 'Las Palmas de Gran Canaria and Santa Cruz de Tenerife',
    Currency: 'Euro',
    'Country Flag': '🇮🇨',
  },

  //East Africa___(9-28)_______________________________________________________________________________________________________
  9: {
    GeoLocation: 'East',
    CountryAbbrv: 'BI',
    CountryName: 'Burundi',
    AreaCode: 257,
    officialLanguage: 'Kirundi',
    Capital: 'Bujumbura',
    Currency: 'Burundi franc',
    'Country Flag': '🇧🇮',
    futureConnections: 157800,
    Population: 10395931,
  },

  10: {
    GeoLocation: 'East',
    CountryAbbrv: 'KM',
    CountryName: 'Comoros',
    AreaCode: 269,
    officialLanguage: 'Arabic',
    Capital: 'Moroni',
    Currency: 'Comorian franc',
    'Country Flag': '🇰🇲',
    futureConnections: 24300,
    Population: 766865,
  },

  11: {
    GeoLocation: 'East',
    CountryAbbrv: 'DJ',
    CountryName: 'Djibouti',
    AreaCode: 253,
    officialLanguage: 'French',
    Capital: 'Djibouti (city)',
    Currency: 'Djiboutian franc',
    'Country Flag': '🇩🇯',
    futureConnections: 25900,
    Population: 810179,
  },

  12: {
    GeoLocation: 'East',
    CountryAbbrv: 'ER',
    CountryName: 'Eritrea',
    AreaCode: 291,
    officialLanguage: 'Afar',
    Capital: 'Asmara',
    Currency: 'Eritrean nakfa',
    'Country Flag': '🇪🇷',
    futureConnections: 200000,
    Population: 6380803,
  },

  13: {
    GeoLocation: 'East',
    CountryAbbrv: 'ET',
    CountryName: 'Ethiopia',
    AreaCode: 251,
    officialLanguage: 'Amharic',
    Capital: 'Addis Ababa',
    Currency: 'Ethiopian birr',
    'Country Flag': '🇪🇹',
    futureConnections: 447300,
    Population: 96633458,
  },

  14: {
    GeoLocation: 'East',
    CountryAbbrv: 'KE',
    CountryName: 'Kenya',
    AreaCode: 254,
    officialLanguage: 'English',
    Capital: 'Nairobi',
    Currency: 'Kenyan shilling',
    'Country Flag': '🇰🇪',
    futureConnections: 3996000,
    Population: 45010056,
  },

  15: {
    GeoLocation: 'East',
    CountryAbbrv: 'MG',
    CountryName: 'Madagascar',
    AreaCode: 261,
    officialLanguage: 'French',
    Capital: 'Antananarivo',
    Currency: 'Malagasy ariary',
    'Country Flag': '🇲🇬',
    futureConnections: 319900,
    Population: 23201926,
  },

  16: {
    GeoLocation: 'East',
    CountryAbbrv: 'MW',
    CountryName: 'Malawi',
    AreaCode: 265,
    officialLanguage: 'Chichewa',
    Capital: 'Lilongwe',
    Currency: 'Malawian kwacha',
    'Country Flag': '🇲🇼',
    futureConnections: 716400,
    Population: 17377468,
  },

  17: {
    GeoLocation: 'East',
    CountryAbbrv: 'MU',
    CountryName: 'Mauritius',
    AreaCode: 230,
    officialLanguage: 'Creole',
    Capital: 'Port Louis',
    Currency: 'Mauritian rupee',
    'Country Flag': '🇲🇺',
    futureConnections: 290000,
    Population: 1331155,
  },

  18: {
    GeoLocation: 'East',
    CountryAbbrv: 'MZ',
    CountryName: 'Mozambique',
    AreaCode: 258,
    officialLanguage: 'Emakhuwa',
    Capital: 'Maputo',
    Currency: 'Mozambican metical',
    'Country Flag': '🇲🇿',
    futureConnections: 613600,
    Population: 24692144,
  },

  19: {
    GeoLocation: 'East',
    CountryAbbrv: 'RW',
    CountryName: 'Rwanda',
    AreaCode: 250,
    officialLanguage: 'Kinyarwanda',
    Capital: 'Kigali',
    Currency: 'Rwandan franc',
    'Country Flag': '🇷🇼',
    futureConnections: 450000,
    Population: 12337138,
  },

  20: {
    GeoLocation: 'East',
    CountryAbbrv: 'SC',
    CountryName: 'Seychelles',
    AreaCode: 248,
    officialLanguage: 'Creole',
    Capital: 'Victoria',
    Currency: 'Seychellois rupee',
    'Country Flag': '🇸🇨',
    futureConnections: 32000,
    Population: 91650,
  },

  21: {
    GeoLocation: 'East',
    CountryAbbrv: 'SO',
    CountryName: 'Somalia',
    AreaCode: 252,
    officialLanguage: 'Somali',
    Capital: 'Mogadishu',
    Currency: 'Somali shilling',
    'Country Flag': '🇸🇴',
    futureConnections: 106000,
    Population: 10428043,
  },

  22: {
    GeoLocation: 'East',
    CountryAbbrv: 'SS',
    CountryName: 'South Sudan',
    AreaCode: 211,
    officialLanguage: 'Arabic',
    Capital: 'Juba',
    Currency: 'South Sudanese Pound',
    'Country Flag': '🇸🇸',
    futureConnections: null,
    Population: 11562695,
  },

  23: {
    GeoLocation: 'East',
    CountryAbbrv: 'TZ',
    CountryName: 'Tanzania',
    AreaCode: 255,
    officialLanguage: 'Kiswahili or Swahili',
    Capital: 'Dodoma',
    Currency: 'Tanzanian shilling',
    'Country Flag': '🇹🇿',
    futureConnections: 678000,
    Population: 49639138,
  },

  24: {
    GeoLocation: 'East',
    CountryAbbrv: 'UG',
    CountryName: 'Uganda',
    AreaCode: 256,
    officialLanguage: 'English',
    Capital: 'Kampala',
    Currency: 'Ugandan shilling',
    'Country Flag': '🇺🇬',
    futureConnections: 3200000,
    Population: 35918915,
  },

  25: {
    GeoLocation: 'East',
    CountryAbbrv: 'ZM',
    CountryName: 'Zambia',
    AreaCode: 260,
    officialLanguage: 'English',
    Capital: 'Lusaka',
    Currency: 'Zambian kwacha',
    'Country Flag': '🇿🇲',
    futureConnections: 816200,
    Population: 14638505,
  },

  26: {
    GeoLocation: 'East',
    CountryAbbrv: 'ZW',
    CountryName: 'Zimbabwe',
    AreaCode: 263,
    officialLanguage: 'English',
    Capital: 'Harare',
    Currency: 'United States Dollar',
    'Country Flag': '🇿🇼',
    futureConnections: 1423000,
    Population: 13771721,
  },

  27: {
    GeoLocation: 'East',
    CountryAbbrv: 'RE',
    CountryName: 'Réunion Island',
    Capital: 'Saint-Denis',
    Currency: 'Euro',
    'Country Flag': '🇷🇪',
  },

  28: {
    GeoLocation: 'East',
    CountryAbbrv: 'YT',
    CountryName: 'Mayotte',
    Capital: 'Mamoudzou',
    Currency: 'Euro',
    'Country Flag': '🇾🇹',
  },

  //South Africa_(29-33)___________________________________________________________________________________________________________________________
  29: {
    GeoLocation: 'South',
    CountryAbbrv: 'BW',
    CountryName: 'Botswana',
    AreaCode: 267,
    officialLanguage: 'Setswana',
    Capital: 'Gaborone',
    Currency: 'Botswana pula',
    'Country Flag': '🇧🇼',
    futureConnections: 120000,
    Population: 2155784,
  },

  30: {
    GeoLocation: 'South',
    CountryAbbrv: 'LS',
    CountryName: 'Lesotho',
    AreaCode: 266,
    officialLanguage: 'Sesotho',
    Capital: 'Maseru',
    Currency: 'Lesotho loti',
    'Country Flag': '🇱🇸',
    futureConnections: 76800,
    Population: 1942008,
  },

  31: {
    GeoLocation: 'South',
    CountryAbbrv: 'NA',
    CountryName: 'Namibia',
    AreaCode: 264,
    officialLanguage: null,
    Capital: 'Windhoek',
    Currency: 'Namibian Dollar',
    'Country Flag': '🇳🇦',
    futureConnections: 127500,
    Population: 2198406,
  },

  32: {
    GeoLocation: 'South',
    CountryAbbrv: 'ZA',
    CountryName: 'South Africa',
    AreaCode: 27,
    officialLanguage: 'IsiZulu',
    Capital: 'Pretoria / Cape Town',
    Currency: 'South African rand',
    'Country Flag': '🇿🇦',
    futureConnections: 4420000,
    Population: 48375645,
  },

  33: {
    GeoLocation: 'South',
    CountryAbbrv: 'SZ',
    CountryName: 'Eswatini',
    AreaCode: 268,
    officialLanguage: 'English',
    Capital: 'Mbabane',
    Currency: 'Swazi lilangeni',
    'Country Flag': '🇸🇿',
    futureConnections: 90100,
    Population: 1419623,
  },

  //West Africa__(34-50)_______________________________________________________________________________________________________________________________
  34: {
    GeoLocation: 'West',
    CountryAbbrv: 'BJ',
    CountryName: 'Benin',
    AreaCode: 229,
    officialLanguage: 'French',
    Capital: 'Porto-Novo',
    Currency: 'West African CFA franc',
    'Country Flag': '🇧🇯',
    futureConnections: 200100,
    Population: 10160556,
  },

  35: {
    GeoLocation: 'West',
    CountryAbbrv: 'BF',
    CountryName: 'Burkina Faso',
    AreaCode: 226,
    officialLanguage: 'French',
    Capital: 'Ouagadougou',
    Currency: 'West African CFA franc',
    'Country Flag': '🇧🇫',
    futureConnections: 178100,
    Population: 18365123,
  },

  36: {
    GeoLocation: 'West',
    CountryAbbrv: 'CV',
    CountryName: 'Cape Verde',
    AreaCode: 238,
    officialLanguage: 'Portuguese',
    Capital: 'Praia',
    Currency: 'Cape Verdean escudo',
    'Country Flag': '🇨🇻',
    futureConnections: 150000,
    Population: 538535,
  },

  37: {
    GeoLocation: 'West',
    CountryAbbrv: 'CI',
    CountryName: "Cote D'Ivoire",
    AreaCode: 225,
    officialLanguage: 'French',
    Capital: 'Yamoussoukro',
    Currency: 'West African CFA franc',
    'Country Flag': '🇨🇮',
    futureConnections: 967300,
    Population: 22848945,
  },

  38: {
    GeoLocation: 'West',
    CountryAbbrv: 'GH',
    CountryName: 'Ghana',
    AreaCode: 233,
    officialLanguage: 'English',
    Capital: 'Accra',
    Currency: 'Ghanaian cedi',
    'Country Flag': '🇬🇭',
    futureConnections: 1297000,
    Population: 25758108,
  },

  39: {
    GeoLocation: 'West',
    CountryAbbrv: 'GM',
    CountryName: 'Gambia',
    AreaCode: 220,
    officialLanguage: 'English',
    Capital: 'Banjul',
    Currency: 'Dalasi',
    'Country Flag': '🇬🇲',
    futureConnections: null,
    Population: 1857181,
  },

  40: {
    GeoLocation: 'West',
    CountryAbbrv: 'GN',
    CountryName: 'Guinea',
    AreaCode: 224,
    officialLanguage: 'French',
    Capital: 'Conakry',
    Currency: 'Guinean franc',
    'Country Flag': '🇬🇳',
    futureConnections: 95000,
    Population: 11474383,
  },

  41: {
    GeoLocation: 'West',
    CountryAbbrv: 'GW',
    CountryName: 'Guinea-Bissau',
    AreaCode: 245,
    officialLanguage: 'Portuguese',
    Capital: 'Bissau',
    Currency: 'West African CFA franc',
    'Country Flag': '🇬🇼',
    futureConnections: 37100,
    Population: 1693398,
  },

  42: {
    GeoLocation: 'West',
    CountryAbbrv: 'LR',
    CountryName: 'Liberia',
    AreaCode: 231,
    officialLanguage: 'English',
    Capital: 'Monrovia',
    Currency: 'Liberian Dollar',
    'Country Flag': '🇱🇷',
    futureConnections: 20000,
    Population: 4092310,
  },

  43: {
    GeoLocation: 'West',
    CountryAbbrv: 'ML',
    CountryName: 'Mali',
    AreaCode: 223,
    officialLanguage: 'French',
    Capital: 'Bamako',
    Currency: 'West African CFA franc',
    'Country Flag': '🇲🇱',
    futureConnections: 249800,
    Population: 16455903,
  },

  44: {
    GeoLocation: 'West',
    CountryAbbrv: 'MR',
    CountryName: 'Mauritania',
    AreaCode: 222,
    officialLanguage: 'Arabic',
    Capital: 'Nouakchott',
    Currency: 'Mauritanian ouguiya',
    'Country Flag': '🇲🇷',
    futureConnections: 75000,
    Population: 3516806,
  },

  45: {
    GeoLocation: 'West',
    CountryAbbrv: 'NE',
    CountryName: 'Niger',
    AreaCode: 227,
    officialLanguage: 'French',
    Capital: 'Niamey',
    Currency: 'West African CFA franc',
    'Country Flag': '🇳🇪',
    futureConnections: 115900,
    Population: 17466172,
  },

  46: {
    GeoLocation: 'West',
    CountryAbbrv: 'NG',
    CountryName: 'Nigeria',
    AreaCode: 234,
    officialLanguage: 'English',
    Capital: 'Abuja',
    Currency: 'Nigerian naira',
    'Country Flag': '🇳🇬',
    futureConnections: 43989000,
    Population: 200963599,
  },

  47: {
    GeoLocation: 'West',
    CountryAbbrv: 'SN',
    CountryName: 'Senegal',
    AreaCode: 221,
    officialLanguage: 'French',
    Capital: 'Dakar',
    Currency: 'West African CFA franc',
    'Country Flag': '🇸🇳',
    futureConnections: 1818000,
    Population: 13635927,
  },

  48: {
    GeoLocation: 'West',
    CountryAbbrv: 'SL',
    CountryName: 'Sierra Leone',
    AreaCode: 232,
    officialLanguage: 'English',
    Capital: 'Freetown',
    Currency: 'Sierra Leonean leone',
    'Country Flag': '🇸🇱',
    futureConnections: 14900,
    Population: 5743725,
  },

  49: {
    GeoLocation: 'West',
    CountryAbbrv: 'TG',
    CountryName: 'Togo',
    AreaCode: 228,
    officialLanguage: 'French',
    Capital: 'Lomé',
    Currency: 'West African CFA franc',
    'Country Flag': '🇹🇬',
    futureConnections: 356300,
    Population: 7351374,
  },

  50: {
    GeoLocation: 'West',
    CountryAbbrv: 'SH',
    CountryName: 'Saint Helena, Ascension and Tristan da Cunha',
    Capital: 'Jamestown',
    Currency: 'Saint Helena pound & pound sterling',
    'Country Flag': '🇸🇭',
  },

  //Central Africa__(51-59)________________________________________________________________________________________________________________________
  51: {
    GeoLocation: 'Central',
    CountryAbbrv: 'AO',
    CountryName: 'Angola',
    AreaCode: 244,
    officialLanguage: 'Portuguese',
    Capital: 'Luanda',
    Currency: 'Angolan kwanza',
    Flag: '🇦🇴',
    futureConnections: 606700,
    Population: 19088106,
  },

  52: {
    GeoLocation: 'Central',
    CountryAbbrv: 'CM',
    CountryName: 'Cameroon',
    AreaCode: 237,
    officialLanguage: 'Major African languages',
    Capital: 'Yaoundé',
    Currency: 'Central African CFA franc',
    'Country Flag': '🇨🇲',
    futureConnections: 749600,
    Population: 23130708,
  },

  53: {
    GeoLocation: 'Central',
    CountryAbbrv: 'CF',
    CountryName: 'Central African Republic',
    AreaCode: 236,
    officialLanguage: 'French',
    Capital: 'Bangui',
    Currency: 'Central African CFA franc',
    'Country Flag': '🇨🇫',
    futureConnections: 22600,
    Population: 5277959,
  },

  54: {
    GeoLocation: 'Central',
    CountryAbbrv: 'TD',
    CountryName: 'Chad',
    AreaCode: 235,
    officialLanguage: 'French',
    Capital: "N'Djamena",
    Currency: 'Central African CFA franc',
    'Country Flag': '🇹🇩',
    futureConnections: 168100,
    Population: 11412107,
  },

  55: {
    GeoLocation: 'Central',
    CountryAbbrv: 'CD',
    CountryName: 'Democratic Republic of the Congo',
    AreaCode: 243,
    officialLanguage: 'French',
    Capital: 'Kinshasa',
    Currency: 'Congolese franc',
    'Country Flag': '🇨🇩',
    futureConnections: 290000,
    Population: 77433744,
  },

  56: {
    GeoLocation: 'Central',
    CountryAbbrv: 'CG',
    CountryName: 'Republic of the Congo',
    AreaCode: 242,
    officialLanguage: 'French',
    Capital: 'Brazzaville',
    Currency: 'Central African CFA franc',
    'Country Flag': '🇨🇬',
    futureConnections: 245200,
    Population: 4662446,
  },

  57: {
    GeoLocation: 'Central',
    CountryAbbrv: 'GQ',
    CountryName: 'Equatorial Guinea',
    AreaCode: 240,
    officialLanguage: 'Spanish',
    Capital: 'Malabo',
    Currency: 'Central African CFA franc',
    'Country Flag': '🇬🇶',
    futureConnections: 14400,
    Population: 722254,
  },

  58: {
    GeoLocation: 'Central',
    CountryAbbrv: 'GA',
    CountryName: 'Gabon',
    AreaCode: 241,
    officialLanguage: 'French',
    Capital: 'Libreville',
    Currency: 'Central African CFA franc',
    'Country Flag': '🇬🇦',
    futureConnections: 98800,
    Population: 1672597,
  },

  59: {
    GeoLocation: 'Central',
    CountryAbbrv: 'ST',
    CountryName: 'Sao Tome And Principe',
    AreaCode: 239,
    officialLanguage: 'Portuguese',
    Capital: 'São Tomé',
    Currency: 'Sao Tome and Principe dobra',
    'Country Flag': '🇸🇹',
    futureConnections: 26700,
    Population: 190428,
  },
};

export default AfricanCountryList;
